### ISSUE TITLE
The program does not work with comma as a decimal separator

### ISSUE THREAD

**Issue by igreenman** [htrb/ngraph-gtk#2]
Thank you for ngraph-gtk.

When I run the program and go to the Help -> Demonstration menu, I get error messages.

Works fine in this launch option: `$ LANG=C ngraph`

My OS: Archlinux

```
$ ngraph -V
Ngraph version 6.08.09
Copyright (C) 2003, Satoshi ISHIZAKA.

  compiler:
    gcc 10.2.0

  library:
    GTK+
     compile: 3.24.24
      linked: 3.24.24

    GLib
     compile: 2.66.4
      linked: 2.66.4

    Cairo
     compile: 1.17.4
      linked: 1.17.4

    Pango
     compile: 1.48.0
      linked: 1.48.0

    GtkSourceView
     compile: 3.24.12
      linked: 3.24.12

    readline
     compile: 8.1
      linked: 8.1

    GSL
     compile: 2.6
      linked: 2.6
```

```
$ locale
LANG=ru_RU.utf8
LC_CTYPE="ru_RU.utf8"
LC_NUMERIC="ru_RU.utf8"
LC_TIME="ru_RU.utf8"
LC_COLLATE="ru_RU.utf8"
LC_MONETARY="ru_RU.utf8"
LC_MESSAGES="ru_RU.utf8"
LC_PAPER="ru_RU.utf8"
LC_NAME="ru_RU.utf8"
LC_ADDRESS="ru_RU.utf8"
LC_TELEPHONE="ru_RU.utf8"
LC_MEASUREMENT="ru_RU.utf8"
LC_IDENTIFICATION="ru_RU.utf8"
LC_ALL=
```

**Comment by htrb** [comment]
Thank you for the report.
As you mentioned, comma cannot be used as a decimal separator in Ngraph-GTK.
Now I am planning to improve the behavior as follows.
* Comma can be used as a decimal separator in a data-file depend on the setting of a data object.
* Only period can be used as a decimal separator in settings (user-interfaces).

**Comment by htrb** [comment]
I have fixed the problem as follows.
* The decimal point symbol can be selected from "period" or "comma" in "Graph"-"Page setup".
** When the decimal point symbol is selected as "period (.)", only the period is recognized as the decimal point symbol in the data file.
** When the decimal point symbol is "comma (,)", both the comma and the period are recognized as the decimal point symbol in the data file.
* The following drawing are depending on the setting of the decimal point symbol.
** Axis scale numbering
** Legend text formatting with %pf
** The printf function and conversion of numbers to strings in a formula conversion.
* The default value of the decimal point symbol can be specified in "Preference"-"Miscellaneous".
** If the default value is "Locale", it will be selected according to the system language setting.

I will release the next version in this month.

**Comment by igreenman** [comment]
Thank you.
