### ISSUE TITLE
データのD&D

### ISSUE THREAD

**Issue by daisukekushida** [htrb/ngraph-gtk#4]
**Describe the bug**
macOS 11.4(Big Sur)にてドラッグ&ドロップでNgraphにデータを読み込みできません．
過去のバージョンまで遡って試したところ，Ver. 6.08.00まではD&Dでデータ(CSVなど)の読み込みが可能ですが，6.08.01からD&Dができなくなっています．「オブジェクト」→「データ」→「追加」→「ファイル」の順だと読み込めます．

**To Reproduce**
1. Ngraph-gtkのアイコンをクリックして起動
2. Finderよりグラフ化したデータ(CSVなど)をNgraphのウィンドウ上にD&D
3. 通常なら〇に+のマークが出てD&D成功するが，そういったマークは表示されずD&Dで読み込みされない

**Expected behavior**
本来であれば，上記3で記すように〇に+のマークが表示されて，D&Dにてデータ(CSVなど)を読み込み可能となる

**Screenshots**
期待する正しい挙動時のスクリーンショットです(Ver.6.08.00)．
<img width="1159" alt="Expected behavior" src="https://user-images.githubusercontent.com/81636081/126859367-d2f158b3-ec86-47ab-a579-5c35e5cd2e0c.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.4 Big Sur

**Additional context**

**Comment by htrb** [comment]
ご報告ありがとうございます。現象を確認しました。
6.08.00 と 6.08.01 の間で DnD 関係の修正はありませんので、GTK の仕様変更によるものではないかと思います。
調査・対応しますので、しばらくお待ちいただけますでしょうか。
よろしくお願い致します。

**Comment by htrb** [comment]
GTK に修正を施すことにより、問題なく Drag and Drop 操作ができるようになりました。
GTK には merge request を出す予定ですが、修正が取り込まれるまで macOS 用パッケージでは独自に修正を加えた GTK を同梱します。
8月か9月に修正された次期バージョンをリリースしようと思います。

**Comment by daisukekushida** [comment]
諸々ご検証いただき，ありがとうございました．
根本の修正はGTKマターのようなので致し方ないですね．
次期バージョンがリリースされましたら試してみます．
