### ISSUE TITLE
M1 Mac Ventureへインストールできない

### ISSUE THREAD

**Issue by daisukekushida** [htrb/ngraph-gtk#5]
(Please use English or 日本語)
**Describe the bug**
M1 MacでVenture（13.0.1）にアップデートしたところ，ngraph-gtkの新規インストールができなくなりました．
パッケージ（dmg）をダウンロードした際は「壊れているため開けません」となります．
Homebrewでインストールを試みましたが，エラーとなりインストールできません（以下参照）．

----- ここから -----
% brew install ngraph-gtk
==> Cloning https://github.com/htrb/ngraph-gtk.git
Updating /Users/xxx/Library/Caches/Homebrew/ngraph-gtk--git
==> Checking out tag v6.09.06
HEAD is now at 942c864b * com.github.htrb.ngraph-gtk.metainfo.xml: update the release information.
HEAD is now at 942c864b * com.github.htrb.ngraph-gtk.metainfo.xml: update the release information.
==> Installing ngraph-gtk from htrb/tap
==> autoreconf -i
Last 15 lines from /Users/xxx/Library/Logs/Homebrew/ngraph-gtk/01.autoreconf:
autoreconf
-i

autopoint: File config.rpath has been locally modified.
autopoint: File m4/gettext.m4 has been locally modified.
autopoint: File m4/host-cpu-c-abi.m4 has been locally modified.
autopoint: File m4/iconv.m4 has been locally modified.
autopoint: File m4/lib-ld.m4 has been locally modified.
autopoint: File m4/lib-link.m4 has been locally modified.
autopoint: File m4/lib-prefix.m4 has been locally modified.
autopoint: File m4/po.m4 has been locally modified.
autopoint: File m4/progtest.m4 has been locally modified.
autopoint: *** Some files have been locally modified. Not overwriting them because --force has not been specified. For your convenience, you find the local modifications in the file '/private/tmp/arVoaIvb/gtnR3dNU/autopoint.diff'.
autopoint: *** Stop.
autoreconf: error: autopoint failed with exit status: 1

Do not report this issue to Homebrew/brew or Homebrew/core!
----- ここまで -----

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Version: [13.0.1]
 - Machine: [M1 Max]

**Comment by htrb** [comment]
ご報告ありがとうございます。
現象を確認しました。
autoreconf のエラーについては -f オプションの追加で解決しました。
その他に Ruby plugin のリンクでエラーになったので、安易な対応ですが Ruby plugin はコンパイルしないようにパッチを追加しました。
手元の環境では正常にインストールできるようになりました。
お試しください。
