### ISSUE TITLE
M1 Mac Venture インストールできない

### ISSUE THREAD

**Issue by userm05** [htrb/ngraph-gtk#6]
M1 Mac Ventura (13.3) において，ngraph-gtk がダウンロードできません．
Homebrew において，

$ brew tap htrb/tap
$ brew install ngraph-gtk

でダウンロードを試みましたが，以下のエラーが発生したためできませんでした．

$ brew install ngraph-gtk
==> Fetching htrb/tap/ngraph-gtk
==> Cloning https://github.com/htrb/ngraph-gtk.git
Updating /Users/username/Library/Caches/Homebrew/ngraph-gtk--git
==> Checking out tag v6.09.07
HEAD is now at cd54b976 * snapcraft.yaml: version 6.09.07 release.
HEAD is now at cd54b976 * snapcraft.yaml: version 6.09.07 release.
==> Installing ngraph-gtk from htrb/tap
==> autoreconf -if
==> ./configure --prefix=/opt/homebrew/Cellar/ngraph-gtk/6.09.07 --libdir=/opt/homebrew
Last 15 lines from /Users/username/Library/Logs/Homebrew/ngraph-gtk/02.configure:
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether clang accepts -g... yes
checking for clang option to enable C11 features... none needed
checking whether clang understands -c and -o together... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking version script options... 
checking for native Win32... no
checking for native OSX... ./configure: line 4224: syntax error near unexpected token `MAC_INTEGRATION,'
./configure: line 4224: `    PKG_CHECK_MODULES(MAC_INTEGRATION, gtk-mac-integration-gtk3)'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/htrb/homebrew-tap/issues

**Comment by htrb** [comment]
残念ながら下記の通り現象を再現できませんでした。
gtk-mac-integration-gtk3 のところでエラーになっているようですが、
gtk-mac-integration-gtk は正しくインストールされているでしょうか（依存関係により自動でインストールされるはずですが）。
あとは自前でソースからビルドしてみると
```
$ brew install ngraph-gtk
==> Fetching htrb/tap/ngraph-gtk
==> Cloning https://github.com/htrb/ngraph-gtk.git
Updating /Users/username/Library/Caches/Homebrew/ngraph-gtk--git
==> Checking out tag v6.09.07
HEAD is now at cd54b976 * snapcraft.yaml: version 6.09.07 release.                                                                                                     
HEAD is now at cd54b976 * snapcraft.yaml: version 6.09.07 release.
==> Installing ngraph-gtk from htrb/tap
==> autoreconf -if
==> ./configure --prefix=/opt/homebrew/Cellar/ngraph-gtk/6.09.07 --libdir=/opt/homebrew/Cellar/ngraph-gtk/6.09.07/lib
==> make
==> make ja.gmo
==> make install
🍺  /opt/homebrew/Cellar/ngraph-gtk/6.09.07: 177 files, 8.4MB, built in 36 seconds
==> Running `brew cleanup ngraph-gtk`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
$ system_profiler SPSoftwareDataType|grep Version
      System Version: macOS 13.3.1 (22E261)
      Kernel Version: Darwin 22.4.0
$ system_profiler SPHardwareDataType|grep Chip
      Chip: Apple M1
```

**Comment by userm05** [comment]
gtk-mac-integration-gtk がインストールされていることの確認はどこからできるでしょうか?

**Comment by htrb** [comment]
`$ brew list`
でインストールされている formulae と casks の一覧が表示されるようです。
その他 Homebrew の使い方については公式ページなどを参照してください。
https://brew.sh/index_ja

**Comment by daisukekushida** [comment]
こんにちは．
私も同様の症状が出ています．
クリーンインストールしたmac(M1 pro)において，brewを使っても手動でコンパイルをしても./configureのところで同様のエラーとなります．
macOS: Ventura 13.3.1

クリーンインストール直後にbrewをインストールし，
$ brew tap htrb/tap
$ brew install ngraph-gtk
とすると，依存関係のパッケージがインストールされますが，./configureで

```
==> ./configure --prefix=/opt/homebrew/Cellar/ngraph-gtk/6.09.07 --libdir=/opt/homebrew/Cellar/ngraph-gtk/6.09.07/lib
Last 15 lines from /Users/kushida/Library/Logs/Homebrew/ngraph-gtk/02.configure:
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether clang accepts -g... yes
checking for clang option to enable C11 features... none needed
checking whether clang understands -c and -o together... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking version script options... 
checking for native Win32... no
checking for native OSX... ./configure: line 4224: syntax error near unexpected token `MAC_INTEGRATION,'
./configure: line 4224: `    PKG_CHECK_MODULES(MAC_INTEGRATION, gtk-mac-integration-gtk3)'
```


となります．当然ながら「gtk-mac-integration」はbrew listで確認すると入っています．
以前Ventura（たぶん，13.1か13.2の頃）で実施した際はエラーは出ず上手くいっていました．
unexpected tokenなので問題の特定が難しく，解決への心当りがあればお知恵を拝借したいです．

ちなみに http://hito.music.coocan.jp/ngraph/ngraph-gtk.html に用意されているarm64版のバイナリーも13.3.1では実行できません（「"ngraph-gtk"は壊れているため開けません。ゴミ箱に入れる必要があります。」となり，ゴミ箱行きかキャンセルしか選択できません）．

ついでにソースコードをダウンロードしていた際に気付きましたが，「Source code(tar.gz)」と「Source code(zip)」は「po/ja.po」の9行目，「po/ngraph-gtk.pot」は9行目および11行目が間違ったままになっていますが，これはこれで良いのでしょうか？

**Comment by htrb** [comment]
ご報告ありがとうございます。
Homebrew を削除してからインストールし直したところ症状を再現できました。
原因は pkg-config パッケージがインストールされないためでした。
pkg-config に依存するように formula を修正しましたので今はインストールできるようになっているはずです(手元では確認済み)。
お試しください。

**Comment by userm05** [comment]
無事インストールする事ができました．
ご対応のほど，ありがとうございました．
