### ISSUE TITLE
特殊文字コードについて

### ISSUE THREAD

**Issue by UyaWatanabe** [htrb/ngraph-gtk#7]
上ドット（Unicode 02D9）を使用したいのですが,Ngraph上でどのように入力すれば良いかわかりません．
ご教示いただけませんでしょうか．

**Comment by htrb** [comment]
Ngraph ではなくご利用のIMEなどの使い方になると思います。
お使いのIMEのマニュアルや下記記事などを参考になさってはいかがでしょうか。
https://qiita.com/toracatman/items/9f609a22b5ad43a4fc4a

あとよく使う記号であれば Ngraph.ini (Windows なら C:\Users\<ユーザ名>\AppData\Local\Ngraph\Ngraph.ini あたり) をエディタで開き「character_map=_Miscellaneous,」と書いてある行を編集すればテキストダイアログの「その他」に記号が表示されるのでクリックして入力できるようになります。
